### ISSUE TITLE
Next.js 프로젝트 참고자료: 앱 라우터 마이그레이션: 좋은 점, 나쁜 점, 그리고 최악인 점 

### ISSUE THREAD

**Issue by k0102575** [WANZARGEN/bundang-baby#4]
### Next.js 프로젝트 참고 자료: 앱 라우터 마이그레이션 - 좋은 점, 나쁜 점, 그리고 최악인 점

기존에 Next.js 프로젝트를 앱 라우터로 마이그레이션한 개발자들의 후기 정보가 차츰 보이기 시작했습니다. 이번에 Korean FE Article에서 관련 내용을 담은 메일이 와서 참고하시라고 이슈로 남깁니다.

- [관련 블로그](https://ktseo41.github.io/blog/log/nextjs-app-router-migration-the-good-bad-and-ugly.html)

실무에서 고려해야 할 사항들이 있지만, 이런 의견들도 있었다는 정도로 참고해 주시면 좋겠습니다.

**Comment by WANZARGEN** [comment]
좋은 정보 감사합니다!!!!!
