### ISSUE TITLE
SVG 사용에 대한 제안

### ISSUE THREAD

**Issue by k0102575** [WANZARGEN/bundang-baby#6]
```
<img src="/bunbebe-logo-full.svg" alt="BunBeBe Logo" />
```

프로젝트 자체에 svg 에 대한 사용처가 많지는 않지만 사용을 최적화 하고자 2가지 개선 제안 사항이 있습니다.

### SVGR 라이브러리 사용
- SVGR is an universal tool to transform SVG into React components.
- SVG 파일을 React 컴포넌트로 변환하여 사용할 수 있게 해주는 라이브러리

[NPM](https://www.npmjs.com/package/@svgr/webpack)
[Dcoument](https://react-svgr.com/docs/what-is-svgr/)

장점: 동적 속성 관리 가능, 재사용성 증가 등
단점: 초기 설정필요, 첫 학습 시간 필요

nextjs 12 버전에서는 이슈가 없었으나 nextjs 14 버전에서는 호환성 체크가 추가로 필요할수도 있을것 같습니다.

### next/image 컴포넌트 사용

- SVGR 을 사용하지 않을경우, 프로젝트에서 img 태그를 사용하는것보다 next/image 컴포넌트 사용을 추천합니다.

장점: 이미지 최적화, 반응형 이미지, Lazy Loading 등 많은 기능 제공
단점: 최적화에 관련된 빌드시간 증가, 추가 설정 필요, 첫 학습시간이 생각보다 오래 걸릴수있음

App Route 현재 Document 기준 제공하는 3가지 컴포넌트 (Image, Link, Script) 중 하나로 
Next.js 로 실무를 진행하게 되면 필수로 학습해야 하는 컴포넌트입니다.
사용은 하지 않더라도 학습해주는게 좋습니다.

[Next.js Image 간단 정리 문서](https://reactnext-central.xyz/blog/nextjs/image-component)

**Comment by WANZARGEN** [comment]
오 좋은 의견 감사요~
